# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/Girls-Coding-Day-Jekyll-blog-4"

# ç½‘é¡µçš„æ ‡é¢˜
title: "Girls Coding Day"
username: yourname
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "æ¶èµ·å¥³æ€§ä¸ç¼–ç¨‹çš„æ¡¥æ¢"

aboutme: "æˆ‘çš„ç”Ÿæ´»ï¼Œå·¥ä½œ ğŸ˜‰ğŸ•ğŸ§"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
